"""empty message

Revision ID: 86920fc30181
Revises: 2b073b8c4559
Create Date: 2019-08-16 20:10:32.859056

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86920fc30181'
down_revision = '2b073b8c4559'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('purchase_date', sa.Integer(), nullable=False),
    sa.Column('confirmation_number', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_name', sa.String(length=30), nullable=True),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('orders_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['orders_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plan_name'),
    sa.UniqueConstraint('price')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('products')
    op.drop_table('orders')
    # ### end Alembic commands ###
